name: RecyclingFoundry
main: fr.frakass.recyclingfoundry.RecyclingFoundry
author: Creepercraft_67
version: 1.2.0
api-version: 1.16

commands:
  recyclingfoundry:
    aliases: rf
    description: Shows plugin help.
